[[configuration]]
generate-gitignore = true
generate-setup-guide = true
generate-courtesy = true
generate-readme = false

[[dependency]]
name = "fasm-mode.el"
path = "/"

[[dependency]]
name = "steel"
path = "hello"